image:
  file: .gitpod.dockerfile

vscode:
  extensions:
    - https://download.zazukoians.org/xrm-shacl-prototype-vscode/xrm-shacl-prototype-1.2.0.vsix

tasks:
  - name: mysql-data-load
    before: gp await-port 3306
    init: |
      mysql < example-database.sql
    command: |
      gp sync-done mysql-data-load
      mysql -e 'SHOW TABLES FROM exampledatabase'
  - name: convert
    init: make install_ontop
    command: |
      gp sync-await mysql-data-load
      make convert
      gp sync-done convert
  - name: pipeline
    before: cd pipeline
    init: npm ci
    command: |
      gp sync-await convert
      npm run pipeline-file
  - name: validate
    before: cd validate
    init: npm ci
    command: |
      gp sync-await pipeline
      npm run validate-file
